
    <link rel="stylesheet" type="text/css" href="<?php echo APPLICATION_URL."tee_script/";?>bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo APPLICATION_URL."tee_script/";?>css/main.css">

    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.css" rel="stylesheet" />
    <!-- The plugins.css -->
    <link rel="stylesheet" type="text/css" href="<?php echo APPLICATION_URL."tee_script/";?>css/plugins.min.css" />
    <!-- The CSS for the plugin itself -->
	<link rel="stylesheet" type="text/css" href="<?php echo APPLICATION_URL."tee_script/";?>css/jquery.fancyProductDesigner.css" />
	<!-- Optional - only when you would like to use custom fonts -->
	<link rel="stylesheet" type="text/css" href="<?php echo APPLICATION_URL."tee_script/";?>css/jquery.fancyProductDesigner-fonts.css" />

    <!-- Include js files -->
	
	<script src="<?php echo APPLICATION_URL."tee_script/";?>bootstrap/js_new/bootstrap.min.js" type="text/javascript"></script>

	<!-- HTML5 canvas library -->
	<script src="<?php echo APPLICATION_URL."tee_script/";?>js_new/fabric.js" type="text/javascript"></script>
	<!-- Third-party plugins that are needed for Fancy Product Designer -->
	<script src="<?php echo APPLICATION_URL."tee_script/";?>js_new/plugins.min.js" type="text/javascript"></script>
	<!-- The plugin itself -->
    <script src="<?php echo APPLICATION_URL."tee_script/";?>js_new/jquery.fancyProductDesigner.js" type="text/javascript"></script>
    <!-- Include only if you would like to create a pdf from your product -->
    <script src="<?php echo APPLICATION_URL."tee_script/";?>jspdf/jspdf.min.js" type="text/javascript"></script>

    <script type="text/javascript">
	    jQuery(document).ready(function(){

	    	var yourDesigner = $('#clothing-designer').fancyProductDesigner({
	    		editorMode: false,
	    		fonts: ['Arial', 'Fearless', 'Helvetica', 'Times New Roman', 'Verdana', 'Geneva', 'Gorditas'],
	    		customTextParameters: {colors: '#000000', removable: true, resizable: true, draggable: true, rotatable: true, autoCenter: true, boundingBox: "Base"},
	    		customImagesParameters: {draggable: true, removable: true, colors: '#000', autoCenter: true, boundingBox: "Base"},
			elementSelect: function(event){
				alert(event);
			}
	    	}).data('fancy-product-designer');
		
	    	//print button
			$('#print-button').click(function(){
				yourDesigner.print();
				return false;
			});

			//create an image
			$('#image-button').click(function(){
				var image = yourDesigner.createImage();
				return false;
			});

			//create a pdf with jsPDF
			$('#pdf-button').click(function(){
				var image = new Image();
				image.src = yourDesigner.getProductDataURL('jpeg', '#ffffff');
				image.onload = function() {
					var doc = new jsPDF();
					doc.addImage(this.src, 'JPEG', 0, 0, this.width * 0.2, this.height * 0.2);
					doc.save('Product.pdf');
				}
				return false;
			});

			//checkout button with getProduct()
			$('#checkout-button').click(function(){
				var product = yourDesigner.getProduct();
				console.log(product);
				return false;
			});

			//event handler when the price is changing
			$('#clothing-designer')
			.bind('priceChange', function(evt, price, currentPrice) {
				$('#thsirt-price').text(currentPrice);
				$('#product_price').val(currentPrice);
			});

			//recreate button
			$('#recreation-button').click(function(){
				var fabricJSON = JSON.stringify(yourDesigner.getFabricJSON());
				$('#recreation-form input:first').val(fabricJSON).parent().submit();
				return false;
			});

			//click handler for input upload
			$('#upload-button').click(function(){
				$('#design-upload').click();
				return false;
			});

			//save image on webserver
			$('#save-image-php').click(function() {
				$.post( "php/save_image.php", { base64_image: yourDesigner.getProductDataURL()} );
			});

			//send image via mail
			$('#send-image-mail-php').click(function() {
				$.post( "php/send_image_via_mail.php", { base64_image: yourDesigner.getProductDataURL()} );
			});

			//upload image
			document.getElementById('design-upload').onchange = function (e) {
				if(window.FileReader) {
					var reader = new FileReader();
			    	reader.readAsDataURL(e.target.files[0]);
			    	reader.onload = function (e) {

			    		var image = new Image;
			    		image.src = e.target.result;
			    		image.onload = function() {
				    		var maxH = 400,
			    				maxW = 300,
			    				imageH = this.height,
			    				imageW = this.width,
			    				scaling = 1;

							if(imageW > imageH) {
								if(imageW > maxW) { scaling = maxW / imageW; }
							}
							else {
								if(imageH > maxH) { scaling = maxH / imageH; }
							}

				    		yourDesigner.addElement('image', e.target.result, 'my custom design', {colors: $('#colorizable').is(':checked') ? '#000000' : false, zChangeable: true, removable: true, draggable: true, resizable: true, rotatable: true, autoCenter: true, boundingBox: "Base", scale: scaling});
			    		};
					};
				}
				else {
					alert('FileReader API is not supported in your browser, please use Firefox, Safari, Chrome or IE10!')
				}
			};
			
			$('.del').click(function(){
				alert('aaa');	
			});
	    });
	    
	    
		
		/*** Price calculation of text addition ***/
		
		
		/*** Price calculation after color change ***/
		
    </script>

    	<div id="main-container" class="container">
          	<h3 id="clothing">Clothing Designer</h3>
		
			<span class="price badge badge-inverse"><span id="thsirt-price"></span> &euro;</span>
			<input type="text" id="product_price">
			<input type="text" id="is_text" value="false" >	
			<input type="text" id="text_price" value="<?php echo $this->txtcost;?>">
			<input type="text" id="img_price" value="<?php echo $this->imgcost;?>">
			<input type="text" id="color_price" value="<?php echo $this->colorcost;?>">
			<input type="text" id="basic_tshirt_color" value="#fffafa">
			<input type="text" id="text_color_price" value="1">
		
          	<div id="clothing-designer">
          		
				<?php
				  $db = new Db();
				//prd($this->product);
				if($this->product!="" && count($this->product)>0) {
					foreach($this->product as $product)	{ 
					$frontimg=$product['image'];
					$backimage=$product['backimage'];
					//echo $Individual_Price=$db->runquery("select * from ".TSHIRT_DISCOUNT." where product_id='".$product['t_cat_id']."' order by no_of_tee asc limit 1");
					//echo "aaaa";die();
				?>
				<?php
					
					if($frontimg!="" and file_exists(SITE_ROOT.'images/tshirtdesigns/front/'.$frontimg) )
					{
						
						$filename=APPLICATION_URL.'images/tshirtdesigns/front/'.$frontimg;
						//$image = imagecreatefromjpeg($filename);
						//	$width = imagesx($image);
						//	$height = imagesy($image);
						//	$pixel = imagecreatetruecolor(1, 1);
						//	imagecopyresampled($pixel, $image, 0, 0, 0, 0, 1, 1, $width, $height);
						//	$rgb = imagecolorat($pixel, 0, 0);
						//	$color = imagecolorsforindex($pixel, $rgb);
						//	print_r($color);
						$c_code = explode(',',$product['colorcode']);
						//echo "<pre>";
						//print_r($product);
						//echo "</pre>";
						//echo $frontimg.">>";
						$Individual_Price=$db->runquery("select * from ".TSHIRT_DISCOUNT." where product_id='".$product['t_cat_id']."' order by no_of_tee asc limit 1");
						
				?>
				<div class="fpd-product" title="Shirt Front" data-thumbnail="<?php echo $filename;?>">
				
					
						<img src="<?php echo $filename; ?>" title="Base" data-parameters='{"x": 325, "y": 329, "colors": "<?php echo $c_code[0];?>", "price": "<?=$Individual_Price[0]['base_price']?>"}' />
						
						<!--<span title="Any Text" data-parameters='{"boundingBox": "Base", "x": 326, "y": 232, "zChangeable": true, "removable": true, "draggable": true, "rotatable": true, "resizable": true, "colors": "#000000"}' >Default Text</span>-->
					<?php
						}
					?>
					
					<?php
					if($backimage!="" and file_exists(SITE_ROOT.'images/tshirtdesigns/back/'.$backimage) )
					{
						
						$imageBack=IMAGES_URL."tshirtdesigns/back/".$backimage;	
					?>
					<div class="fpd-product" title="Shirt Back" data-thumbnail="<?php echo $imageBack;?>">
						<img src="<?php echo $imageBack;?>" title="Base" data-parameters='{"x": 317, "y": 329, "colors": "Base", "price": 0}' />
						<!--<span title="Any Text" data-parameters='{"boundingBox": "Base", "x": 326, "y": 232, "zChangeable": true, "removable": true, "draggable": true, "rotatable": true, "resizable": true, "colors": "#000000"}' >Default 1111</span>-->
					</div>
					<?php }?>
				</div>
				
				<?php
				} }
				?>
				
		  		<div class="fpd-design">
		  			<div class="fpd-category" title="Swirls">
			  			<img src="<?php echo APPLICATION_URL."tee_script/";?>images/designs/swirl.png" title="Swirl" data-parameters='{"zChangeable": true, "x": 215, "y": 200, "colors": "#000000", "removable": true, "draggable": true, "rotatable": true, "resizable": true, "price": 10, "boundingBox": "Base", "autoCenter": true}' />
				  		<img src="<?php echo APPLICATION_URL."tee_script/";?>images/designs/swirl2.png" title="Swirl 2" data-parameters='{"x": 215, "y": 200, "colors": "#000000", "removable": true, "draggable": true, "rotatable": true, "resizable": true, "price": 5, "boundingBox": "Base", "autoCenter": true}' />
				  		<img src="<?php echo APPLICATION_URL."tee_script/";?>images/designs/swirl3.png" title="Swirl 3" data-parameters='{"x": 215, "y": 200, "colors": "#000000", "removable": true, "draggable": true, "rotatable": true, "resizable": true, "autoCenter": true}' />
				  		<img src="<?php echo APPLICATION_URL."tee_script/";?>images/designs/heart_blur.png" title="Heart Blur" data-parameters='{"x": 215, "y": 200, "colors": "#bf0200", "removable": true, "draggable": true, "rotatable": true, "resizable": true, "price": 5, "boundingBox": "Base", "autoCenter": true}' />
				  		<img src="<?php echo APPLICATION_URL."tee_script/";?>images/designs/converse.png" title="Converse" data-parameters='{"x": 215, "y": 200, "colors": "#000000", "removable": true, "draggable": true, "rotatable": true, "resizable": true, "autoCenter": true}' />
				  		<img src="<?php echo APPLICATION_URL."tee_script/";?>images/designs/crown.png" title="Crown" data-parameters='{"x": 215, "y": 200, "colors": "#000000", "removable": true, "draggable": true, "rotatable": true, "resizable": true, "autoCenter": true}' />
				  		<img src="<?php echo APPLICATION_URL."tee_script/";?>images/designs/men_women.png" title="Men hits Women" data-parameters='{"x": 215, "y": 200, "colors": "#000000", "removable": true, "draggable": true, "rotatable": true, "resizable": true, "boundingBox": "Base", "autoCenter": true}' />
		  			</div>
		  			<div class="fpd-category" title="Retro">
			  			<img src="<?php echo APPLICATION_URL."tee_script/";?>images/designs/retro_1.png" title="Retro One" data-parameters='{"x": 210, "y": 200, "colors": "#000000", "removable": true, "draggable": true, "rotatable": true, "resizable": true, "scale": 0.25, "price": 7, "boundingBox": "Base", "autoCenter": true}' />
				  		<img src="<?php echo APPLICATION_URL."tee_script/";?>images/designs/retro_2.png" title="Retro Two" data-parameters='{"x": 193, "y": 180, "colors": "#ffffff", "removable": true, "draggable": true, "rotatable": true, "resizable": true, "scale": 0.46, "boundingBox": "Base", "autoCenter": true}' />
				  		<img src="<?php echo APPLICATION_URL."tee_script/";?>images/designs/retro_3.png" title="Retro Three" data-parameters='{"x": 240, "y": 200, "colors": "#000000", "removable": true, "draggable": true, "rotatable": true, "resizable": true, "scale": 0.25, "price": 8, "boundingBox": "Base", "autoCenter": true}' />
				  		<img src="<?php echo APPLICATION_URL."tee_script/";?>images/designs/heart_circle.png" title="Heart Circle" data-parameters='{"x": 240, "y": 200, "colors": "#007D41", "removable": true, "draggable": true, "rotatable": true, "resizable": true, "scale": 0.4, "boundingBox": "Base", "autoCenter": true}' />
				  		<img src="<?php echo APPLICATION_URL."tee_script/";?>images/designs/swirl.png" title="Swirl" data-parameters='{"x": 215, "y": 200, "colors": "#000000", "removable": true, "draggable": true, "rotatable": true, "resizable": true, "price": 10, "boundingBox": "Base", "autoCenter": true}' />
				  		<img src="<?php echo APPLICATION_URL."tee_script/";?>images/designs/swirl2.png" title="Swirl 2" data-parameters='{"x": 215, "y": 200, "colors": "#000000", "removable": true, "draggable": true, "rotatable": true, "resizable": true, "price": 5, "boundingBox": "Base", "autoCenter": true}' />
				  		<img src="<?php echo APPLICATION_URL."tee_script/";?>images/designs/swirl3.png" title="Swirl 3" data-parameters='{"x": 215, "y": 200, "colors": "#000000", "removable": true, "draggable": true, "rotatable": true, "resizable": true}' />
				  	</div>
		  		</div>
		  	</div>
		  	<br />
		  	<div class="row">
			  	<!--<div class="api-buttons col-md-7"> 
				  	<a href="#" id="print-button" class="btn btn-primary">Print</a>
				  	<a href="#" id="image-button" class="btn btn-primary">Create Image</a>
				  	<a href="#" id="pdf-button" class="btn btn-primary">Create PDF</a>
				  	<a href="#" id="checkout-button" class="btn btn-success">Checkout</a>
				  	<a href="#" id="recreation-button" class="btn btn-success">Recreate product</a>
			  	</div>
			  	<div class="col-md-2">
			  		<a href="#" id="upload-button" class="btn btn-warning">Upload own design</a>
				  	<label class="checkbox inline"><input type="checkbox" id="colorizable" /> Colorizable?</label>
			  	</div>-->
			  	
		  	</div>

		  	<!--<h4>Only working on a webserver:</h4>
		  	<button class="btn btn-info" id="save-image-php">Save image with php</button>
		  	<button class="btn btn-info" id="send-image-mail-php">Send image to mail</button>-->

		  	<!-- The form recreation -->
		  	<input type="file" id="design-upload" style="display: none;" />
			<form action="php/recreation.php" id="recreation-form" method="post">
				<input type="hidden" name="recreation_product" value="" />
			</form>

    	</div>
   
    <script src="<?php echo APPLICATION_URL."tee_script/";?>js_new/editor_custom.js" type="text/javascript"></script>
